# Generated by Django 4.2.1 on 2023-06-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_cart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
